import { MenuItem } from '../src/types';

export const MENU_ITEMS: MenuItem[] = [
  {
    id: 'honey-cinnamon-oat-latte',
    name: 'Honey Cinnamon Oat Latte',
    category: 'espresso',
    description: 'Double shot of velvety espresso layered with micro-foamed oat milk, raw local wildflower honey, and freshly ground Saigon cinnamon.',
    price: 5.95,
    calories: 190,
    caffeineMg: 150,
    caffeineLevel: 'medium',
    flavorNotes: ['sweet cinnamon', 'wild honey', 'toasted oats', 'creamy'],
    roastOrigin: 'Guatemala Antigua & Ethiopian Blend',
    dietaryTags: ['dairy-free', 'nut-free', 'organic'],
    allergens: ['oats'],
    milkOptions: ['Oat Milk (Default)', 'Almond Milk', 'Soy Milk', 'Whole Milk', 'Skim Milk'],
    sweetnessLevels: ['100% Standard', '50% Half Sweet', '25% Light Sweet', 'Sugar-Free Monkfruit'],
    temperatureOptions: ['hot', 'iced'],
    availableAddOns: [
      { name: 'Extra Espresso Shot', price: 1.00, calories: 5 },
      { name: 'Collagen Protein Boost', price: 1.50, calories: 45 },
      { name: 'House Vanilla Bean Syrup', price: 0.75, calories: 40 }
    ],
    inStock: true,
    isPopular: true,
    image: 'https://images.unsplash.com/photo-1541167760496-1628856ab772?auto=format&fit=crop&w=600&q=80'
  },
  {
    id: 'nitro-cold-brew-salted-foam',
    name: 'Nitro Cold Brew with Salted Cream Foam',
    category: 'cold-brew',
    description: 'Steeped for 20 hours with single-origin Colombian beans, nitrogen-infused for a stout-like cascade, crowned with velvety sea-salted vanilla cold foam.',
    price: 6.25,
    calories: 140,
    caffeineMg: 280,
    caffeineLevel: 'high',
    flavorNotes: ['dark chocolate', 'brown sugar', 'sea salt', 'silky cream'],
    roastOrigin: 'Huila, Colombia',
    dietaryTags: ['nut-free', 'low-sugar'],
    allergens: ['dairy (in foam - optional oat foam available)'],
    milkOptions: ['Dairy Cold Foam (Default)', 'Oat Milk Cold Foam', 'No Foam / Black'],
    sweetnessLevels: ['Unsweetened Base + Sweet Foam', 'Zero Sugar Caramel Foam', 'Extra Sweet'],
    temperatureOptions: ['iced'],
    availableAddOns: [
      { name: 'Oat Cold Foam Upgrade', price: 0.75, calories: 60 },
      { name: 'Sugar-Free Hazelnut Pump', price: 0.75, calories: 0 },
      { name: 'CBD Wellness Drop (15mg)', price: 2.00, calories: 0 }
    ],
    inStock: true,
    isPopular: true,
    image: 'https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?auto=format&fit=crop&w=600&q=80'
  },
  {
    id: 'single-origin-ethiopian-pourover',
    name: 'Ethiopian Yirgacheffe Pour-Over (V60)',
    category: 'pour-over',
    description: 'Masterfully hand-dripped filter brew showcasing vibrant jasmine florals, bergamot citrus, and honeyed peach notes. Clean, tea-like body.',
    price: 6.50,
    calories: 5,
    caffeineMg: 180,
    caffeineLevel: 'medium',
    flavorNotes: ['jasmine blossom', 'bergamot', 'white peach', 'meyer lemon'],
    roastOrigin: 'Yirgacheffe, Ethiopia (Gedeo Zone, 2100m)',
    dietaryTags: ['vegan', 'dairy-free', 'gluten-free', 'keto', 'organic', 'nut-free'],
    allergens: [],
    milkOptions: ['None / Black (Recommended)', 'Splash of Oat Milk', 'Splash of Almond Milk'],
    sweetnessLevels: ['Unsweetened (Recommended)', 'Light Honey (+0.50)'],
    temperatureOptions: ['hot', 'iced'],
    availableAddOns: [
      { name: 'Artisan Glass Server Service', price: 0.00, calories: 0 },
      { name: 'Pair with Lemon Shortbread', price: 3.25, calories: 180 }
    ],
    inStock: true,
    isPopular: true,
    image: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=600&q=80'
  },
  {
    id: 'ceremonial-matcha-oat-latte',
    name: 'Ceremonial Uji Matcha Oat Latte',
    category: 'tea-matcha',
    description: 'First-harvest stone-ground Japanese Uji matcha whisked with gentle steamed oat milk and a hint of organic Madagascar vanilla.',
    price: 6.50,
    calories: 160,
    caffeineMg: 70,
    caffeineLevel: 'low',
    flavorNotes: ['umami', 'sweet grassy', 'vanilla', 'creamy'],
    roastOrigin: 'Kyoto Prefecture, Japan',
    dietaryTags: ['vegan', 'dairy-free', 'nut-free', 'organic'],
    allergens: ['oats'],
    milkOptions: ['Oat Milk (Default)', 'Almond Milk', 'Coconut Milk', 'Whole Milk'],
    sweetnessLevels: ['Light Vanilla (Default)', 'Unsweetened Pure', 'Standard Sweet', 'Monkfruit Sweet'],
    temperatureOptions: ['hot', 'iced'],
    availableAddOns: [
      { name: 'Lavender Blossom Infusion', price: 0.85, calories: 25 },
      { name: 'Mushroom Adaptogen Blend (Reishi + Lion\'s Mane)', price: 1.75, calories: 15 },
      { name: 'Extra Matcha Shot (Double Strength)', price: 1.50, calories: 5 }
    ],
    inStock: true,
    isPopular: true,
    image: 'https://images.unsplash.com/photo-1536256263959-770b48d82b0a?auto=format&fit=crop&w=600&q=80'
  },
  {
    id: 'spanish-pistachio-cortado',
    name: 'Pistachio Rose Cortado',
    category: 'espresso',
    description: 'Equal parts bold ristretto espresso and velvety steamed almond milk, lightly infused with roasted Sicilian pistachio paste and a whisper of organic rose water.',
    price: 5.25,
    calories: 110,
    caffeineMg: 130,
    caffeineLevel: 'medium',
    flavorNotes: ['roasted pistachio', 'rose water', 'cocoa nib', 'caramel'],
    roastOrigin: 'Brazilian Cerrado / Sumatra Dark Blend',
    dietaryTags: ['dairy-free', 'vegan', 'gluten-free'],
    allergens: ['tree nuts (pistachio, almond)'],
    milkOptions: ['Almond Milk (Default)', 'Oat Milk', 'Whole Milk'],
    sweetnessLevels: ['Subtle Sweet (Default)', 'Unsweetened', 'Extra Pistachio (+0.75)'],
    temperatureOptions: ['hot', 'iced'],
    availableAddOns: [
      { name: 'Crushed Sicilian Pistachio Rim', price: 0.50, calories: 20 },
      { name: 'Extra Ristretto Shot', price: 1.00, calories: 5 }
    ],
    inStock: true,
    isSeasonal: true,
    image: 'https://images.unsplash.com/photo-1534778101976-62847782c213?auto=format&fit=crop&w=600&q=80'
  },
  {
    id: 'swiss-water-decaf-flat-white',
    name: 'Swiss Water Decaf Velvet Flat White',
    category: 'espresso',
    description: '100% chemical-free Swiss Water processed Colombian Supremo beans pulled as double ristretto with micro-gloss steamed milk. Full richness, zero jitters.',
    price: 5.45,
    calories: 120,
    caffeineMg: 4,
    caffeineLevel: 'decaf',
    flavorNotes: ['milk chocolate', 'roasted hazelnut', 'toffee', 'velvety'],
    roastOrigin: 'Antioquia, Colombia (Swiss Water Decaf)',
    dietaryTags: ['nut-free', 'gluten-free'],
    allergens: ['milk (can sub oat/almond)'],
    milkOptions: ['Whole Milk (Default)', 'Oat Milk', 'Almond Milk', 'Coconut Milk'],
    sweetnessLevels: ['Unsweetened (Classic)', 'Light Caramel', 'Vanilla Sugar-Free'],
    temperatureOptions: ['hot', 'iced'],
    availableAddOns: [
      { name: 'Cardamom Spice Dusting', price: 0.35, calories: 2 },
      { name: 'Extra Decaf Shot', price: 1.00, calories: 5 }
    ],
    inStock: true,
    image: 'https://images.unsplash.com/photo-1577968897966-3d4325b36b61?auto=format&fit=crop&w=600&q=80'
  },
  {
    id: 'hibiscus-yuzu-sparkling-refresher',
    name: 'Sparkling Hibiscus Yuzu Botanicals',
    category: 'tea-matcha',
    description: 'Cold-steeped organic ruby hibiscus tea shaken with Japanese yuzu juice, sparkling mineral water, and fresh mint sprigs. Crisp, hydrating, antioxidant-rich.',
    price: 5.50,
    calories: 45,
    caffeineMg: 0,
    caffeineLevel: 'decaf',
    flavorNotes: ['tart hibiscus', 'citrus yuzu', 'fresh mint', 'fizzy'],
    roastOrigin: 'Oaxaca, Mexico & Kochi, Japan',
    dietaryTags: ['vegan', 'dairy-free', 'gluten-free', 'low-sugar', 'nut-free', 'organic'],
    allergens: [],
    milkOptions: ['None'],
    sweetnessLevels: ['Light Agave (Default)', 'Unsweetened Crisp', 'Extra Sweet'],
    temperatureOptions: ['iced'],
    availableAddOns: [
      { name: 'Chia Seed Hydration Boost', price: 0.75, calories: 30 },
      { name: 'Ginger Root Extract', price: 0.50, calories: 5 }
    ],
    inStock: true,
    isPopular: true,
    image: 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?auto=format&fit=crop&w=600&q=80'
  },
  {
    id: 'keto-mct-bulletproof-americano',
    name: 'Keto Brain-Fuel MCT Americano',
    category: 'espresso',
    description: 'Rich triple-shot Americano blended high-speed with organic C8 MCT oil, grass-fed ghee (or coconut butter), and a dash of Himalayan pink salt.',
    price: 6.75,
    calories: 220,
    caffeineMg: 225,
    caffeineLevel: 'high',
    flavorNotes: ['rich dark cocoa', 'creamy coconut', 'smoky oak', 'salted butter'],
    roastOrigin: 'Sumatra Mandheling & Papua New Guinea',
    dietaryTags: ['keto', 'gluten-free', 'low-sugar', 'nut-free'],
    allergens: ['dairy (ghee) or tree nut (coconut)'],
    milkOptions: ['Grass-fed Ghee & MCT (Default)', 'Vegan Coconut Butter & MCT', 'Heavy Cream'],
    sweetnessLevels: ['Unsweetened (Keto Standard)', 'Monkfruit Vanilla Drop', 'Stevia Cinnamon'],
    temperatureOptions: ['hot', 'iced'],
    availableAddOns: [
      { name: 'Grass-fed Collagen Peptides (10g)', price: 1.50, calories: 40 },
      { name: 'L-Theanine Focus Boost', price: 1.00, calories: 0 }
    ],
    inStock: true,
    image: 'https://images.unsplash.com/photo-1511920170033-f8396924c348?auto=format&fit=crop&w=600&q=80'
  },
  {
    id: 'smoked-vanilla-bourbon-cold-brew',
    name: 'Smoked Bourbon Vanilla Cold Brew',
    category: 'seasonal',
    description: 'Oak-barrel aged cold brew infused with whole smoked Madagascar vanilla pods, topped with charred orange peel essence and brown sugar reduction.',
    price: 6.95,
    calories: 90,
    caffeineMg: 260,
    caffeineLevel: 'high',
    flavorNotes: ['oak barrel', 'smoked vanilla', 'candied orange', 'molasses'],
    roastOrigin: 'Guatemala Huehuetenango',
    dietaryTags: ['vegan', 'dairy-free', 'nut-free'],
    allergens: [],
    milkOptions: ['None / Black (Recommended)', 'Oat Milk Splash', 'Almond Milk Splash'],
    sweetnessLevels: ['Standard Infusion', 'Half Sweet', 'Unsweetened'],
    temperatureOptions: ['iced'],
    availableAddOns: [
      { name: 'Bourbon Barrel Cold Foam', price: 1.00, calories: 70 },
      { name: 'Espresso Float', price: 1.00, calories: 5 }
    ],
    inStock: true,
    isSeasonal: true,
    isPopular: true,
    image: 'https://images.unsplash.com/photo-1461023058943-07fcbe16d735?auto=format&fit=crop&w=600&q=80'
  },
  {
    id: 'vegan-banana-walnut-loaf',
    name: 'Artisan Vegan Banana Walnut Loaf',
    category: 'bakery',
    description: 'Moist banana bread baked with organic bananas, toasted California walnuts, coconut nectar, and cinnamon crunch top. 100% plant-based.',
    price: 4.50,
    calories: 310,
    caffeineMg: 0,
    caffeineLevel: 'decaf',
    flavorNotes: ['ripe banana', 'toasted walnut', 'cinnamon sugar', 'caramelized crust'],
    dietaryTags: ['vegan', 'dairy-free', 'organic'],
    allergens: ['tree nuts (walnuts)', 'wheat/gluten'],
    milkOptions: [],
    sweetnessLevels: [],
    temperatureOptions: ['hot'], // warmed or room temp
    availableAddOns: [
      { name: 'Warmed with Whipped Vegan Butter', price: 0.50, calories: 50 },
      { name: 'Almond Butter Drizzle', price: 0.75, calories: 85 }
    ],
    inStock: true,
    isPopular: true,
    image: 'https://images.unsplash.com/photo-1608039829572-78524f79c4c7?auto=format&fit=crop&w=600&q=80'
  },
  {
    id: 'avocado-sourdough-tartine',
    name: 'Avocado & Meyer Lemon Sourdough Tartine',
    category: 'savory',
    description: 'Thick cut toasted country sourdough, smashed Hass avocados, pickled shallots, microgreens, extra virgin olive oil, and Maldon smoked sea salt flakes.',
    price: 8.95,
    calories: 380,
    caffeineMg: 0,
    caffeineLevel: 'decaf',
    flavorNotes: ['creamy avocado', 'tangy sourdough', 'pickled shallot', 'lemon zest'],
    dietaryTags: ['vegan', 'dairy-free', 'nut-free', 'organic'],
    allergens: ['wheat/gluten'],
    milkOptions: [],
    sweetnessLevels: [],
    temperatureOptions: ['hot'],
    availableAddOns: [
      { name: 'Pasture-Raised Poached Egg', price: 1.75, calories: 75 },
      { name: 'Gluten-Free Seed Bread Sub', price: 1.50, calories: 40 },
      { name: 'Chili Crunch Drizzle', price: 0.50, calories: 35 }
    ],
    inStock: true,
    isPopular: true,
    image: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&w=600&q=80'
  },
  {
    id: 'almond-croissant-valrhona',
    name: 'Twice-Baked Valrhona Almond Croissant',
    category: 'bakery',
    description: 'Flaky buttery croissant filled with rich almond frangipane cream and French Valrhona dark chocolate batons, encrusted with toasted sliced almonds.',
    price: 5.25,
    calories: 420,
    caffeineMg: 10,
    caffeineLevel: 'decaf',
    flavorNotes: ['flaky butter', 'sweet frangipane', 'dark chocolate', 'toasted almond'],
    dietaryTags: ['organic'],
    allergens: ['wheat/gluten', 'dairy (butter)', 'tree nuts (almonds)', 'eggs'],
    milkOptions: [],
    sweetnessLevels: [],
    temperatureOptions: ['hot'],
    availableAddOns: [
      { name: 'Warmed in French Oven', price: 0.00, calories: 0 }
    ],
    inStock: true,
    isPopular: true,
    image: 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?auto=format&fit=crop&w=600&q=80'
  }
];
